name: Deploy Next JS Application
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "MONGO_URL = ${{ secrets.MONGO_URL }}" >> .env
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/next-docker-aws-ec2-cicd .
      - name: Login to Dockerhub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish image to Dockerhub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/next-docker-aws-ec2-cicd

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Dockerhub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/next-docker-aws-ec2-cicd
      - name: Delete the old container
        run: docker rm -f nextjs-app-container
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name nextjs-app-container ${{ secrets.DOCKER_USERNAME }}/next-docker-aws-ec2-cicd
